services:
  pokedex:
    build: .
    ports:
      - "8000:8000"
    env-file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:latest
    env-file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
